### ISSUE TITLE
Can I fix the result?

### ISSUE THREAD

**Issue by Tataro** [WreewanMorhee/ReactRoulette#1]
Hi,
Just wonder that if I want the prize which is fetched from the server-side before roll the game, is it possible?

**Comment by WreewanMorhee** [comment]
Hi Tataro
thank u for your issue

this is not allowed currently
I think I can make it possible recently

**Comment by WreewanMorhee** [comment]
Hi Tataro
If you still here

I think that you can fix this issue
But I lost my webpack(and other related file like babel) , so if you want to fix that maybe you should build the new webpack file first
sorry about that

**Comment by Tataro** [comment]
Hi @WreewanMorhee 
My apologize for the late reply. I already solved the issue by add some logic base on your sourcecode.

Thanks a lot!
